# Generated by Django 6.0.5 on 2026-06-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_it_support',
            field=models.BooleanField(default=False),
        ),
    ]
