# Generated by Django 6.0.5 on 2026-06-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_userprofile_is_it_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('IT', 'واحد IT'), ('MGMT', 'مدیریت')], default='IT', max_length=10),
        ),
    ]
